In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
import numpy as np 

In [2]:
!pip install numpy

In [3]:
np.__version__

'1.19.5'

vector or 1D Array

In [4]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

Matrix 0r 2D Array

In [5]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a = np.array([1,2,3,4,5,6,7])
a [0]

1

In [7]:
a[2:5]

array([3, 4, 5])

In [8]:
l = [1,2,3,4,5,6,7]
l[0]

1

In [9]:
l[2:5]

[3, 4, 5]

In [10]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [11]:
l[:6]

[1, 2, 3, 4, 5, 6]

In [12]:
a[3:]

array([4, 5, 6, 7])

In [13]:
a[-1]

7

In [14]:
a[-2]

6

In [15]:
l[-1]

7

In [16]:
a[2:-3]

array([3, 4])

In [17]:
l[2:-3]

[3, 4]

In [18]:
a[-5:]

array([3, 4, 5, 6, 7])

In [19]:
a[-5:-1]

array([3, 4, 5, 6])

In [20]:
a[-1:2]

array([], dtype=int64)

In [21]:
np.size(a)

7

In [22]:
np.shape(a)

(7,)

In [23]:
a[a[2]]

4

In [24]:
l[l[3]]

5

In [25]:
l.reverse()
l

[7, 6, 5, 4, 3, 2, 1]

ใน array ไม่มีคำสั่ง reverse 
ให้ใช้ sorted แทน

In [26]:
sorted(a, reverse=True)

[7, 6, 5, 4, 3, 2, 1]

In [27]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
np.shape(a)

(7,)

In [29]:
a = a.reshape(1,7)
np.shape(a)

(1, 7)

In [30]:
a

array([[1, 2, 3, 4, 5, 6, 7]])

In [31]:
a[0,0]

1

In [32]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
a[:,-1]

array([3, 6, 9])

In [34]:
a[:,0]

array([1, 4, 7])

In [35]:
a[:,1] = 0
a

array([[1, 0, 3],
       [4, 0, 6],
       [7, 0, 9]])

In [36]:
a[0:2,:] =8
a

array([[8, 8, 8],
       [8, 8, 8],
       [7, 0, 9]])

In [37]:
a.shape

(3, 3)

In [38]:
a.size

9

In [39]:
np.size(a,1)

3

In [40]:
np.ndim(a)

2

In [41]:
a.ndim

2

In [42]:
a[:,0] = 4
a

array([[4, 8, 8],
       [4, 8, 8],
       [4, 0, 9]])

In [43]:
a[1,:] = 5
a

array([[4, 8, 8],
       [5, 5, 5],
       [4, 0, 9]])

In [44]:
y = np.zeros((2,3,4))
y.ndim

3

In [45]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [46]:
a = np.array(np_mix_matrix[:,1], dtype=int)
a

array([2, 4, 6])

In [47]:
a = np.zeros((5,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
a = np.ones((10))
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [49]:
c = np.ones((5,5))*8
c

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

In [50]:
d = np.eye(5,5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
c*d


array([[8., 0., 0., 0., 0.],
       [0., 8., 0., 0., 0.],
       [0., 0., 8., 0., 0.],
       [0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 8.]])

In [52]:
np.empty([20,20])

array([[4.04738577e-320, 1.89721208e-321, 0.00000000e+000,
        4.65712483e-310, 4.94065646e-324, 4.65712483e-310,
                    nan, 6.90755797e-310, 4.94065646e-324,
        0.00000000e+000, 4.94065646e-324, 6.90730850e-310,
        4.65712483e-310, 6.90755874e-310, 4.94065646e-324,
        4.94065646e-324, 4.94065646e-324, 4.65712483e-310,
        9.88131292e-324, 4.65712483e-310],
       [4.65712483e-310, 4.65693196e-310, 4.65712254e-310,
        8.39911598e-323, 4.65712254e-310, 2.12199579e-313,
        8.39911598e-323, 4.65712254e-310, 8.39911598e-323,
        4.65712254e-310, 2.75859453e-313, 1.43279037e-322,
        4.65712483e-310, 4.94065646e-324, 4.65712483e-310,
        1.90979621e-313, 0.00000000e+000, 0.00000000e+000,
        6.90730850e-310, 4.65712483e-310],
       [4.65712483e-310, 4.65712483e-310, 4.94065646e-324,
        1.08694442e-322, 4.65712483e-310, 1.42290906e-321,
        4.44659081e-323, 6.90749937e-310, 4.65712287e-310,
        4.94065646e-324, 9.88

In [53]:
def addone(a):
    return a + 1

In [54]:
addone(a)

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

เลขที่สุ่มออกมาจะอยู่ในช่วงระหว่าง 0-1

In [55]:
rng = np.random.RandomState(0)
rng.rand()

0.5488135039273248

In [56]:
[np.round(np.random.rand()*10) for item in range(10)]

[10.0, 4.0, 6.0, 8.0, 9.0, 4.0, 9.0, 7.0, 6.0, 9.0]

In [57]:
np.random.randint(5)

4

In [58]:
np.random.seed (0)
[np.random.randint(5) for item in range(10)]

[4, 0, 3, 3, 3, 1, 3, 2, 4, 0]

In [59]:
np.random.rand(5,5)

array([[0.96366276, 0.38344152, 0.79172504, 0.52889492, 0.56804456],
       [0.92559664, 0.07103606, 0.0871293 , 0.0202184 , 0.83261985],
       [0.77815675, 0.87001215, 0.97861834, 0.79915856, 0.46147936],
       [0.78052918, 0.11827443, 0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561, 0.77423369, 0.45615033]])

In [60]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

array([3, 1, 1, 5, 6])

In [61]:

a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace=False)

array([ 4,  8,  3, 10,  9])

In [62]:
np_matrix = np.round(np.random.rand(1000,5))
np_matrix

array([[1., 1., 0., 1., 1.],
       [0., 0., 1., 1., 0.],
       [0., 1., 1., 1., 1.],
       ...,
       [0., 1., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 1.]])

In [63]:
idx_choose = np.random.choice(1000,100, replace = False)
idx_choose

array([846,   1, 757, 697, 480, 820, 907, 592, 798, 346, 338, 313, 830,
       605, 842, 774, 995, 860, 407, 934, 603,  11, 730, 344, 182, 843,
       558,  49, 371, 458, 731, 191, 132, 746, 668, 629, 120,  95, 232,
        59, 252,  86, 196, 323, 612, 859, 768,  39, 938, 822, 555, 914,
       941, 213,  25, 168, 851, 190, 899, 420, 531, 452, 894, 651, 882,
       688, 494, 331, 349, 376, 789, 996, 790,  82, 465, 632, 486,  34,
        23, 985, 259, 381, 616, 779, 971, 960, 710, 327, 980, 581,   9,
       813, 388, 121, 755,  10, 933, 628, 165, 487])

In [64]:
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[1., 0., 0., 1., 0.],
       [0., 0., 1., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 1., 1., 1.],
       [0., 0., 1., 1., 0.],
       [1., 1., 1., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 0., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 0.],
       [1., 0., 0., 1., 1.],
       [0., 1., 0., 1., 1.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 0., 0.],
       [0., 1., 1., 1., 1.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 1., 1., 0.],
       [1., 0.

# Ex 2. Randomly create a matrix of size (10, 5) then randomly assign values of 0 and 1 to the last column of this matrix.


In [65]:
np_matrix = np.random.rand(10,5)
np_matrix[:,4] = np.round(np_matrix[:,4])
np_matrix

array([[0.11502806, 0.99405473, 0.44164615, 0.91527128, 0.        ],
       [0.99030617, 0.05930393, 0.05892232, 0.82323714, 1.        ],
       [0.24793679, 0.24684592, 0.47265508, 0.94360254, 1.        ],
       [0.83252966, 0.86710342, 0.13444939, 0.57880853, 1.        ],
       [0.09564527, 0.44354644, 0.76485332, 0.98957706, 0.        ],
       [0.4044393 , 0.75296056, 0.59407994, 0.87865307, 0.        ],
       [0.54251256, 0.60919391, 0.81426454, 0.84562256, 0.        ],
       [0.60432491, 0.00785273, 0.68902902, 0.01544607, 1.        ],
       [0.50589605, 0.95405972, 0.16307401, 0.38377673, 1.        ],
       [0.51409537, 0.81462434, 0.50742545, 0.682402  , 1.        ]])

In [66]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

array([[10,  9,  0,  2,  5],
       [ 6,  5, 10,  7,  7],
       [ 7,  8,  1,  0,  8],
       [ 2,  7,  5,  2,  8],
       [ 9, 10,  6, 10,  7]])

In [67]:
row,column = np.where(np_matrix == 2)
[(row[i],column[i]) for i in range(len(row))]

[(0, 3), (3, 0), (3, 3)]

In [68]:
i,j = np.where(np_matrix == 2)
[(i[ii],j[ii]) for ii in range(len(i))]

[(0, 3), (3, 0), (3, 3)]

# Ex 3. Why we cannot use this index ? Please fix it !!
idx = [1,2,3,4,5]
np_matrix[idx,:]

In [83]:
idx = [1,2,3,4,5]
np_matrix[len(idx)-1,:]

array([ 9, 10,  7])

random เวอ์ชั่นใหม่
> 

In [70]:
rng = np.random.RandomState(0)
np_matrixe = rng.randint(3,size = (5,5))
np_matrix

array([[10,  9,  0,  2,  5],
       [ 6,  5, 10,  7,  7],
       [ 7,  8,  1,  0,  8],
       [ 2,  7,  5,  2,  8],
       [ 9, 10,  6, 10,  7]])

In [71]:
np_matrix = np.delete(np_matrix,[1,2],1)
np_matrix

array([[10,  2,  5],
       [ 6,  7,  7],
       [ 7,  0,  8],
       [ 2,  2,  8],
       [ 9, 10,  7]])

In [72]:
np_matrix

array([[10,  2,  5],
       [ 6,  7,  7],
       [ 7,  0,  8],
       [ 2,  2,  8],
       [ 9, 10,  7]])

In [73]:
a = np_matrix == 2
a

array([[False,  True, False],
       [False, False, False],
       [False, False, False],
       [ True,  True, False],
       [False, False, False]])

In [74]:
np_matrix[a] = 99
np_matrix

array([[10, 99,  5],
       [ 6,  7,  7],
       [ 7,  0,  8],
       [99, 99,  8],
       [ 9, 10,  7]])

# Ex 4. Randomly create a data matrix of 10 samples with 5 features. 
# Then, randomly create a label vector for 10 samples. 
# Finally, seperate samples into 2 groups
# Group 1 called train_data (label == 0)
# Group 2 called test_data (label == 1)

In [84]:
matrix = np.random.randint(10,size = (10,5))
matrix

array([[5, 1, 5, 4, 2],
       [2, 2, 6, 1, 3],
       [9, 6, 7, 8, 3],
       [1, 8, 3, 7, 5],
       [4, 6, 4, 3, 5],
       [7, 2, 8, 5, 7],
       [3, 9, 0, 2, 8],
       [5, 1, 6, 8, 1],
       [3, 7, 0, 2, 0],
       [5, 4, 5, 6, 7]])

In [85]:
label_vector = np.random.randint(2,size = 10)
label_vector

array([0, 1, 1, 1, 0, 1, 0, 0, 0, 0])

In [86]:
train_data = matrix[np.where(label_vector == 0)]
train_data

array([[5, 1, 5, 4, 2],
       [4, 6, 4, 3, 5],
       [3, 9, 0, 2, 8],
       [5, 1, 6, 8, 1],
       [3, 7, 0, 2, 0],
       [5, 4, 5, 6, 7]])

In [87]:

test_data = matrix[np.where(label_vector == 1)]
test_data

array([[2, 2, 6, 1, 3],
       [9, 6, 7, 8, 3],
       [1, 8, 3, 7, 5],
       [7, 2, 8, 5, 7]])